wechat:
  appid: wx2ecebcda3a0b1938
  secret: 017bad7964ddc755c7bafa74e6e719ff
  token: kkjoe
  aesKey:

logging:
  level:
    root: info
    com.bootdo: debug


socket:
  host: 0.0.0.0
  port: 9092

redis:
  #  host: 192.168.1.175
  host: 127.0.0.1
  port: 6379
  password: 123123


spring:
  redis:
    host: localhost
    port: 6379
    password: 123123
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1